name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |        
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build Image
      run: |
        docker build -t eze2286/graphql-actions:0.0.1 .
    - name: Push Docker Image
      run: |
        docker push eze2286/graphql-actions:0.0.1
    
      
    
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
